run:
  deadline: 2m30s
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close,github.com/yandex-cloud/terraform-provider-yandex/yandex:Set
  govet:
    disable:
      - copylocks

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - staticcheck
      text: "SA4010:"
